config/routes.rb
Rails.application.routes.draw do
  resources :applications, only: [ :new, :create] do
    resources :steps, only: [:show, :update], controller: 'application/steps'
  end
  devise_for :users
  root to: 'pages#home'
  get 'school', to: "pages#school"
  get 'information', to: "pages#information"
  get 'pedagogie', to: "pages#pedagogie"
  get 'programme', to: "pages#programme"
  get 'contact', to: "pages#contact"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

      <!-- Links when logged in -->
      <%= link_to "L'école", school_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Informations", information_path, class: "navbar-wagon-item navbar-wagon-link"  %>
      <%= link_to "La pédagogie", pedagogie_path, class: "navbar-wagon-item navbar-wagon-link"  %>
      <%= link_to "Les programmes", programme_path, class: "navbar-wagon-item navbar-wagon-link"  %>
      <%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-wagon-link"  %>
    </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li> <%= link_to "L'école", school_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Informations", information_path, class: "navbar-wagon-item navbar-wagon-link"  %></li>
        <li><%= link_to "La pédagogie", pedagogie_path, class: "navbar-wagon-item navbar-wagon-link"  %></li>
        <li> <%= link_to "Les programmes", programme_path, class: "navbar-wagon-item navbar-wagon-link"  %></li>
        <li><%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-wagon-link"  %></li>
      </ul>
    </div>
  </div>
</div>